Download NTK Datasets 

In [1]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('stopwords')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping chunkers\maxent_ne_chunker.zip.
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

Text preprocessing 

In [5]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
import nltk

# Force re-download of punkt (even if partially downloaded earlier)
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [10]:
import nltk
nltk.download('punkt')



[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [12]:
# Import core NLP and data libraries
import nltk
import spacy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from wordcloud import WordCloud

# Download required NLTK resources (only needed once)
nltk.download('punkt')                      # Tokenizer
nltk.download('averaged_perceptron_tagger') # POS tagger
nltk.download('maxent_ne_chunker')          # Named Entity Chunker
nltk.download('words')                      # Word list for NER
nltk.download('stopwords')                  # Stopwords

# Import tokenizers and stopwords
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import ngrams

# Load spaCy English model
nlp = spacy.load("en_core_web_sm")


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [17]:
# 1. Install required libraries if not already installed
# Uncomment and run once if using a new environment
# !pip install nltk spacy matplotlib wordcloud scikit-learn pandas

# 2. Import all necessary libraries
import nltk
import spacy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 3. Download required NLTK data
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('stopwords')

# 4. Import tokenizers and stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk import ngrams

# 5. Load spaCy English model
nlp = spacy.load("en_core_web_sm")

# -------------------------------
# ✅ TEXT PREPROCESSING STARTS HERE
# -------------------------------

# Sample text
text = "Natural Language Processing is a fascinating field of Artificial Intelligence!"

# Step 1: Convert text to lowercase
text = text.lower()

# Step 2: Tokenize using NLTK
try:
    tokens = word_tokenize(text)
except LookupError:
    print("word_tokenize failed. Falling back to spaCy.")
    doc = nlp(text)
    tokens = [token.text for token in doc]

# Step 3: Remove stopwords and punctuation
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word.isalpha() and word not in stop_words]

# Show results
print("Original Tokens:", tokens)
print("Filtered Tokens (after preprocessing):", filtered_tokens)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mukit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


word_tokenize failed. Falling back to spaCy.
Original Tokens: ['natural', 'language', 'processing', 'is', 'a', 'fascinating', 'field', 'of', 'artificial', 'intelligence', '!']
Filtered Tokens (after preprocessing): ['natural', 'language', 'processing', 'fascinating', 'field', 'artificial', 'intelligence']


2. Tokenization and N-grams

In [19]:
from nltk import ngrams

# Assuming filtered_tokens contains the cleaned tokens from previous step
cleaned_tokens = filtered_tokens

# Generate bigrams (2-grams)
bigrams = list(ngrams(cleaned_tokens, 2))

print("Bigrams:", bigrams)


Bigrams: [('natural', 'language'), ('language', 'processing'), ('processing', 'fascinating'), ('fascinating', 'field'), ('field', 'artificial'), ('artificial', 'intelligence')]


3. Named Entity Recognition (NER)

Use spaCy to perform NER on a new sentence.

In [20]:
# Example sentence
sentence = "Barack Obama was born in Hawaii and was elected president in 2008."

# Process the sentence with spaCy's NLP pipeline
doc = nlp(sentence)

# Extract and print named entities and their labels
for ent in doc.ents:
    print(ent.text, ent.label_)


Barack Obama PERSON
Hawaii GPE
2008 DATE


4. Converting Text to Numbers

Use CountVectorizer and TfidfVectorizer to convert a list of sentences into numeric vectors.

In [21]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

sentences = [
    "I love machine learning.",
    "Natural language processing is a part of AI.",
    "AI is the future."
]

# CountVectorizer: Converts text to a matrix of token counts
count_vec = CountVectorizer()
X_count = count_vec.fit_transform(sentences)
print("Count Vectorizer Output:\n", X_count.toarray())
print("Feature Names:", count_vec.get_feature_names_out())

# TfidfVectorizer: Converts text to a matrix of TF-IDF features
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(sentences)
print("\nTF-IDF Vectorizer Output:\n", X_tfidf.toarray())
print("Feature Names:", tfidf_vec.get_feature_names_out())


Count Vectorizer Output:
 [[0 0 0 0 1 1 1 0 0 0 0 0]
 [1 0 1 1 0 0 0 1 1 1 1 0]
 [1 1 1 0 0 0 0 0 0 0 0 1]]
Feature Names: ['ai' 'future' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'of'
 'part' 'processing' 'the']

TF-IDF Vectorizer Output:
 [[0.         0.         0.         0.         0.57735027 0.57735027
  0.57735027 0.         0.         0.         0.         0.        ]
 [0.30650422 0.         0.30650422 0.40301621 0.         0.
  0.         0.40301621 0.40301621 0.40301621 0.40301621 0.        ]
 [0.42804604 0.5628291  0.42804604 0.         0.         0.
  0.         0.         0.         0.         0.         0.5628291 ]]
Feature Names: ['ai' 'future' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'of'
 'part' 'processing' 'the']


5. Word Embeddings (Advanced)
Use spaCy to get word vectors (embeddings) for given words.

In [22]:
import spacy

# Load the medium English model (has word vectors)
nlp = spacy.load("en_core_web_md")

# Get the vector for the word "machine"
word = nlp("machine")[0]  # First token
print("Vector for 'machine':\n", word.vector)
print("Vector shape:", word.vector.shape)  # Should be (300,)


Vector for 'machine':
 [-0.72883    0.20718   -0.0033379 -0.0027673 -0.17204    0.023277
  0.1297    -0.2112     0.32876    0.67447    0.10047   -0.30559
  0.11213    0.22959   -0.32997    0.1389    -0.57289    2.523
 -0.32921    0.06045    0.23895    0.1091     0.19358   -0.1765
  0.11583    0.63204   -0.13644   -0.24354    0.20061   -0.50244
  0.40537   -0.38688    0.73784    0.093937  -0.30643    0.045874
  0.097915  -0.082114   0.13082   -0.039022   0.088084  -0.27023
 -0.077658  -0.0045355  0.18986   -0.063083  -0.138      0.40474
 -0.16199   -0.10953    0.22923   -0.67634   -0.65763   -0.044595
 -0.12119    0.071167   0.25993   -0.27052   -0.22474   -0.13818
  0.20692    0.87604   -0.35257   -0.1498     0.72804    0.68768
  0.19993    0.084733  -0.2234     0.11301    0.29895   -0.090119
  0.038172  -0.32912    0.014221  -0.36335    0.5898     0.10467
  0.16549    0.47199    0.078939  -0.19985    0.84014   -0.2277
 -0.22907   -0.26243   -0.32598    1.0146    -0.079235  -0.34248
  